### Site Settings ###
title               : Jordan Frecon-Deloire
description         : >-
                      Associate Professor in Machine Learning
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : jordanfrecon/jordanfrecon.github.io
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji
  - jekyll-include-cache
  - jekyll/scholar
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-link-attributes
  - jekyll-twitter-plugin

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/test.md


### Author Info ###
author:
  name              : Jordan Frecon-Deloire
  image             : images/identity.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : jordan.frecon@gmail.com
#  facebook          : your_username
  github            : jordanFrecon
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
#  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  publications:
    output: true
    permalink: /:collection/:name
  news:
    output: true
    permalink: /:collection/:name
  bibliography:
    output: true
    permalink: /bibliography/:name
  teaching:
    output: true
    permalink: /:collection/:name
  courses:
    output: true
    permalink: /:collection/:name

### Disqus ###
disqus: jfrecon                          # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "courses"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  
  
### Jekyll scholar ###
scholar:

  last_name: [Frecon]
  first_name: [Jordan, J.]

  style: apa
  locale: en

  source: /_publications/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

badges: # Display different badges for your pulications
  altmetric_badge: true # Altmetric badge (https://www.altmetric.com/products/altmetric-badges/)
  dimensions_badge: true # Dimensions badge (https://badge.dimensions.ai/)

# Filter out certain bibtex entry keywords used internally from the bib output
filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website, preview, altmetric]

# Maximum number of authors to be shown for each publication (more authors are visible on click)
max_author_limit: 3  # leave blank to always show all authors
more_authors_animation_delay: 10  # more authors are revealed on click using animation; smaller delay means faster animation
 

